In [1]:
import numpy as np
from pickle import load

In [2]:
knn_classifier = load(open('D:/saikrishna data science/MLFLOW/model/decision_tree_model.pkl', 'rb'))
lr_classifier = load(open('D:/saikrishna data science/MLFLOW/model/knn_model.pkl', 'rb'))
nb_classifier = load(open('D:/saikrishna data science/MLFLOW/model/lr_model.pkl', 'rb'))
random = load(open('D:/saikrishna data science/MLFLOW/model/rf_model.pkl', 'rb'))
sv_classifier = load(open('D:/saikrishna data science/MLFLOW/model/svr.pkl', 'rb'))
scaler = load(open('D:/saikrishna data science/MLFLOW/model/scaler.pkl', 'rb'))

In [3]:
clarity_encoder = {'I1':1, 'SI2':2, 'SI1':3, 'VS2':4, 'VS1':5, 'VVS2':6, 'VVS1':7, 'IF':8}
color_encoder = {'J':1, 'I':2, 'H':3, 'G':4, 'F':5, 'E':6, 'D':7}
cut_encoder = {'Fair' : 1, 'Good' : 2, 'Very Good' : 3, 'Ideal' : 4, 'Premium' : 5}
      

In [4]:
clarity_encoder.keys()

dict_keys(['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF'])

In [5]:
color_encoder.keys()

dict_keys(['J', 'I', 'H', 'G', 'F', 'E', 'D'])

In [6]:
num_scal=scaler.transform([[0.55 ,59.8 ,58.0 ,3.95 ,4.35,2.31 ]])
num_scal.flatten()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([-0.52323107, -1.35758759,  0.24206962, -1.58956348, -1.20413701,
       -1.77506194])

In [7]:
cat_encod=np.array([clarity_encoder["SI2"],color_encoder["D"],cut_encoder["Very Good"]])
cat_encod

array([2, 7, 3])

In [8]:
rf = np.concatenate((num_scal.flatten(),cat_encod), axis=None).reshape(1,-1)
rf

array([[-0.52323107, -1.35758759,  0.24206962, -1.58956348, -1.20413701,
        -1.77506194,  2.        ,  7.        ,  3.        ]])

In [11]:
random.predict(rf)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([1184.36666667])